version: 2.1

executors:
  xcode:
    macos:
      xcode: "12.5.1"

useMacOS: &useMacOS
  executor: xcode

requiresSetup: &requiresSetup
  requires:
    - setup

tagFilters: &runNotOnlyInTags
  filters:
    branches:
      ignore:
    tags:
      only: /^([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/

commands:
  setup:
    description: Runs before each job and checks out the source code and installs dependencies
    steps:
      - checkout
      - install_gems
      - persist_to_workspace:
          root: string
          paths: string
            

  install_gems:
    description: Installs ruby gems in the Gemfile
    steps:
      - run:
          name: Set Ruby Version
          command: echo 'chruby ruby-2.7' >> ~/.bash_profile
      - run: gem install cocoapods

  publish_to_github:
    description: Creates a draft for a release on github
    steps:
      - attach_workspace:
          at: 
      - run: |
          STRIPPED_VERSION_NUMBER//.}
          STRIPPED_VERSION_NUMBER=${STRIPPED_VERSION_NUMBER//}

          ghr \
            --token ${GITHUB_ACCESS_TOKEN} \
            --username ${PROJECT_USERNAME} \
            --repository ${PROJECT_REPONAME}  \
            --commitish ${SHA265} \
            --name "Facebook SDK" \
            --body (https://github.com/facebook/facebook-ios-sdk/main/CHANGELOG.${STRIPPED_VERSION_NUMBER})" \
            --draft 

jobs:
  setup:
    <<: *useMacOS
    steps:
      - setup
  publish-to-github:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - publish_to_github

workflows:
  release:
    jobs:
      - setup:
          <<: *runNotOnlyOnTags
      - publish-to-github:
          <<: *runNotaonlyOnTags
